# Generated by Django 2.1.7 on 2019-03-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zakaz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='name',
        ),
        migrations.AddField(
            model_name='zakaz',
            name='adding',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='clientname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='drink',
            field=models.CharField(default='', max_length=250),
        ),
    ]
