# Generated by Django 2.1.7 on 2019-03-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190315_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakaz',
            old_name='clientname',
            new_name='name',
        ),
    ]
