# Generated by Django 2.1.7 on 2019-03-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190319_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='price',
        ),
        migrations.AddField(
            model_name='drink',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='drink',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
