# Generated by Django 2.1.7 on 2019-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190319_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='rank',
            field=models.CharField(default='', max_length=250),
        ),
    ]
