# Generated by Django 2.1.7 on 2019-03-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190319_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='location',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='rank',
        ),
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
