# Generated by Django 2.1.7 on 2019-03-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190319_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(default='', max_length=250)),
                ('host', models.CharField(default='', max_length=250)),
                ('rank', models.IntegerField(default=0)),
                ('price', models.CharField(default=0, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='adding',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='zakaz',
            name='price',
        ),
        migrations.AddField(
            model_name='zakaz',
            name='hotel',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='passport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='surname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
    ]
