# Generated by Django 2.1.7 on 2019-04-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190329_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='hotels'),
        ),
    ]
